export const TREE_THEME_COLORS = {
  'editor.background': '#ede5d3',
  'editor.foreground': '#141410',
  'sideBar.background': '#ede5d3',
  'sideBar.foreground': '#141410',
  'list.activeSelectionBackground': '#d9cfba',
  'list.activeSelectionForeground': '#141410',
  'list.hoverBackground': '#d9cfba80',
  'list.hoverForeground': '#141410',
  focusBorder: '#a53030',
  'input.background': '#d9cfba',
  'input.foreground': '#141410',
  'input.border': '#b8ac9a',
  'input.placeholderForeground': '#6b645a',
  'gitDecoration.addedResourceForeground': '#2a7e4f',
  'gitDecoration.modifiedResourceForeground': '#a53030',
  'gitDecoration.deletedResourceForeground': '#d4636f',
  'gitDecoration.untrackedResourceForeground': '#6b645a',
  'gitDecoration.ignoredResourceForeground': '#b8ac9a',
}
