/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksSlugRouteImport } from './routes/tasks/$slug'
import { Route as TasksSlugIndexRouteImport } from './routes/tasks/$slug/index'
import { Route as TasksSlugFilesSplatRouteImport } from './routes/tasks/$slug/files/$'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksSlugRoute = TasksSlugRouteImport.update({
  id: '/tasks/$slug',
  path: '/tasks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksSlugIndexRoute = TasksSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksSlugRoute,
} as any)
const TasksSlugFilesSplatRoute = TasksSlugFilesSplatRouteImport.update({
  id: '/files/$',
  path: '/files/$',
  getParentRoute: () => TasksSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/tasks/$slug': typeof TasksSlugRouteWithChildren
  '/tasks/$slug/': typeof TasksSlugIndexRoute
  '/tasks/$slug/files/$': typeof TasksSlugFilesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/tasks/$slug': typeof TasksSlugIndexRoute
  '/tasks/$slug/files/$': typeof TasksSlugFilesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/tasks/$slug': typeof TasksSlugRouteWithChildren
  '/tasks/$slug/': typeof TasksSlugIndexRoute
  '/tasks/$slug/files/$': typeof TasksSlugFilesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/tasks/$slug'
    | '/tasks/$slug/'
    | '/tasks/$slug/files/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs' | '/tasks/$slug' | '/tasks/$slug/files/$'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/tasks/$slug'
    | '/tasks/$slug/'
    | '/tasks/$slug/files/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  TasksSlugRoute: typeof TasksSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$slug': {
      id: '/tasks/$slug'
      path: '/tasks/$slug'
      fullPath: '/tasks/$slug'
      preLoaderRoute: typeof TasksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$slug/': {
      id: '/tasks/$slug/'
      path: '/'
      fullPath: '/tasks/$slug/'
      preLoaderRoute: typeof TasksSlugIndexRouteImport
      parentRoute: typeof TasksSlugRoute
    }
    '/tasks/$slug/files/$': {
      id: '/tasks/$slug/files/$'
      path: '/files/$'
      fullPath: '/tasks/$slug/files/$'
      preLoaderRoute: typeof TasksSlugFilesSplatRouteImport
      parentRoute: typeof TasksSlugRoute
    }
  }
}

interface TasksSlugRouteChildren {
  TasksSlugIndexRoute: typeof TasksSlugIndexRoute
  TasksSlugFilesSplatRoute: typeof TasksSlugFilesSplatRoute
}

const TasksSlugRouteChildren: TasksSlugRouteChildren = {
  TasksSlugIndexRoute: TasksSlugIndexRoute,
  TasksSlugFilesSplatRoute: TasksSlugFilesSplatRoute,
}

const TasksSlugRouteWithChildren = TasksSlugRoute._addFileChildren(
  TasksSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  TasksSlugRoute: TasksSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
